apiVersion: messaging.knative.dev/v1alpha1
kind: Sequence
metadata:
  name: chat-pipeline
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    # kind: KafkaChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: lemmanizer-fr
    - ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: emojizer
  reply:
    kind: Service
    apiVersion: serving.knative.dev/v1alpha1
    name: cloudevents-logger
