apiVersion: messaging.knative.dev/v1alpha1
kind: Sequence
metadata:
  name: chat-pipline
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    # kind: InMemoryChannel
    kind: KafkaChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: lemmanizer-fr
    - ref:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        name: emojizer
  reply:
    kind: Broker
    apiVersion: eventing.knative.dev/v1alpha1
    name: default