apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: debug-pipeline
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: debug-pipeline-trigger
spec:
  filter:
    sourceAndType:
      type: com.ruggedcode.chat.message.text
#  filter:
#    sourceAndType:
#      type: samples.http.mod3
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: debug-pipeline