version: '2'

vars:
  VERSION: $(cat VERSION.txt)

tasks:
  default:
    deps: [deploy]

  deploy:
    deps: [slackit]
    cmds:
      - ./service.yaml.sh

  slackit:
    cmds:
      - docker build -t hbouvier/slackit:{{.VERSION}} .
      - docker push hbouvier/slackit:{{.VERSION}}
    status:
      - docker pull hbouvier/slackit:{{.VERSION}}
