version: '2'

vars:
  VERSION: v0.0.26

tasks:
  default:
    deps: [deploy]

  emoji:
    cmds:
      - docker build -t hbouvier/emojizer:{{.VERSION}} -f Dockerfile .
      - docker push hbouvier/emojizer:{{.VERSION}}
    status:
      - docker pull hbouvier/emojizer:{{.VERSION}}

  deploy:
    deps: [emoji]
    cmds:
      - kubectl apply -f service.yml