version: '2'

vars:
  VERSION: v0.0.8

tasks:
  default:
    deps: [emoji]

  emoji:
    cmds:
      - docker build -t hbouvier/emojizer:{{.VERSION}} -f Dockerfile .
      - docker push hbouvier/emojizer:{{.VERSION}}
    status:
      - docker pull hbouvier/emojizer:{{.VERSION}}
