name: Python package

on: [push]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ubuntu-stretch
    strategy:
      max-parallel: 3
      matrix:
        # python-version: [3.5, 3.6, 3.7]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd emoji && pip install -r requirements.txt
#    - name: Lint with flake8
#      run: |
#        pip install flake8
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
    - name: Build docker container
      run: |
        docker build -t docker.pkg.github.com/hbouvier/knative-simple-chat/emojizer:latest -f emoji/Dockerfile emoji/
    - name: Publish to Registry
      run: |
        apt-get -y install pass
        curl -fsSL "https://github.com/docker/docker-credential-helpers/releases/download/v0.6.0/docker-credential-pass-v0.6.0-amd64.tar.gz" | tar xv
        chmod + $(pwd)/docker-credential-pass

        gpg --batch --gen-key <<-EOF ; pass init $(gpg --no-auto-check-trustdb --list-secret-keys | grep ^sec | cut -d/ -f2 | cut -d" " -f1)
        %echo Generating a standard key
        Key-Type: DSA
        Key-Length: 1024
        Subkey-Type: ELG-E
        Subkey-Length: 1024
        Name-Real: Meshuggah Rocks
        Name-Email: meshuggah@example.com
        Expire-Date: 0
        # Do a commit here, so that we can later print "done" :-)
        %commit
        %echo done
        EOF

        echo "${DOCKER_PASSWORD}" | docker login docker.pkg.github.com --username $DOCKER_USERNAME --password-stdin
        docker push docker.pkg.github.com/hbouvier/knative-simple-chat/emojizer:latest
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}


        #  DOCKER_REGISTRY_URL: docker.pkg.github.com
        #  DOCKER_USERNAME: ${{ github.actor }}
        #  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
